### ISSUE TITLE
id

### ISSUE THREAD

**Issue by gdedi001** [josegarban/Dasmoto#2]
Fantastic job opting for the `id` attribute in conjunction with the `<div>` tag. This was arguably the best approach to take! 
https://github.com/josegarban/Dasmoto/blob/master/index.html#L14
https://github.com/josegarban/Dasmoto/blob/master/index.html#L26
https://github.com/josegarban/Dasmoto/blob/master/index.html#L38

**Comment by josegarban** [comment]
Thanks! I did it this way because each header had a different color.
