### ISSUE TITLE
alt attribute

### ISSUE THREAD

**Issue by gdedi001** [josegarban/Dasmoto#3]
The `alt` attribute is primarily used for accessibility with a screen reader. Make sure to fill it in.
https://github.com/josegarban/Dasmoto/blob/master/index.html#L16

[What is alt used for](https://www.w3schools.com/TAGS/att_img_alt.asp)

**Comment by josegarban** [comment]
Thanks for the feedback. I have just updated the code to include the `alt` attribute in all three instances.
