### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by gdedi001** [josegarban/Dasmoto#4]
_Grade: Exceeds Expectations_

Fantastic job on your project, you were able to use `<div>` tags correctly in conjunction with `id` attribute. In addition to this, you were able to meet the requirements based on the provided design mock. An area for improvement is with your `alt` attributes. Make sure to fill them in. 

A recommendation here to review the following article and make a mental note of the advice given. As your projects get more complex, articles like this will most definitely come in handy. Keep up the stellar work!
https://www.webpagefx.com/blog/web-design/20-html-best-practices-you-should-follow/

**Comment by josegarban** [comment]
Thanks for all the feedback!
